### ISSUE TITLE
vdr-xineliboutput médialeátszás szegmentációs hiba

### ISSUE THREAD

**Issue by attuska** [attuska/vdr4uhu#1]
DVB eszköz nincs, xine-lib-1.8
nvidia-GF210 nouveau, vagy nvidia-340 -el.
"-Pxineliboutput --hud -t" opcióval.

Thread 1 "vdr" received signal SIGSEGV, Segmentation fault.
0x00007fffdbb14f35 in xine_post_wire_audio_port () from /usr/lib/libxine.so.2
(gdb) bt
#0  0x00007fffde883f35 in xine_post_wire_audio_port () from /usr/lib/libxine.so.2
#1  0x00007fffdead9fe3 in fe_post_unwire () from /usr/lib/vdr/libxineliboutput-sxfe.so.2.1.0
#2  0x00007fffdeadafb5 in fe_control.part () from /usr/lib/vdr/libxineliboutput-sxfe.so.2.1.0
#3  0x00007fff848993c6 in close_slave_stream () from /usr/lib/xine/plugins/2.6/xineplug_inp_xvdr.so
#4  0x00007fff848998d8 in handle_control_playfile () from /usr/lib/xine/plugins/2.6/xineplug_inp_xvdr.so
#5  0x00007fff8489c808 in vdr_plugin_parse_control () from /usr/lib/xine/plugins/2.6/xineplug_inp_xvdr.so
#6  0x00007fffee7e0be3 in cXinelibLocal::Xine_Control(char const*) [clone .part.3] () from /usr/lib/vdr/libvdr-xineliboutput.so.2.4.0
#7  0x00007fffee7c7e78 in cXinelibThread::PlayFile(char const*, int, bool, ePlayMode, int) ()
   from /usr/lib/vdr/libvdr-xineliboutput.so.2.4.0
#8  0x00007fffee7c4ff2 in cXinelibDevice::PlayFile(char const*, int, bool, ePlayMode, int) ()
   from /usr/lib/vdr/libvdr-xineliboutput.so.2.4.0
#9  0x00007fffee7dd602 in cXinelibPlayer::Activate(bool) () from /usr/lib/vdr/libvdr-xineliboutput.so.2.4.0
#10 0x00007fffee7dd8a9 in cXinelibPlayer::~cXinelibPlayer() () from /usr/lib/vdr/libvdr-xineliboutput.so.2.4.0
#11 0x00007fffee7dd8e9 in cXinelibPlayer::~cXinelibPlayer() () from /usr/lib/vdr/libvdr-xineliboutput.so.2.4.0
#12 0x00007fffee7dbaeb in cXinelibPlayerControl::Close() () from /usr/lib/vdr/libvdr-xineliboutput.so.2.4.0
#13 0x00007fffee7dbb38 in cXinelibPlayerControl::~cXinelibPlayerControl() () from /usr/lib/vdr/libvdr-xineliboutput.so.2.4.0
#14 0x00007fffee7dbb59 in cXinelibPlayerControl::~cXinelibPlayerControl() () from /usr/lib/vdr/libvdr-xineliboutput.so.2.4.0
#15 0x00000000004e1543 in cControl::Shutdown() ()
#16 0x00000000004713ee in main ()
(gdb)

**Comment by attuska** [comment]
xine-lib-1.9 -el ugyanez.
A vdr-plugin beállításokban a hangot letilva is ugyanez.

**Comment by attuska** [comment]
Találtam valamit: https://lists.gnu.org/archive/html/bug-readline/2016-04/msg00041.html
A readline -t elláttam fedora foltokkal, de nem segített.
https://src.fedoraproject.org/cgit/rpms/readline.git
Ezek szerint Fedora esetében is rossz lenne, vagy valami más a bűnös és nem a readline?
